### ISSUE TITLE
Noob question: How do I get this to work?

### ISSUE THREAD

**Issue by gjvnq** [casbin/casbin-rs#186]
I am trying to use casbin but the lack of documentation and examples has made things a bit confusing for me.

I am trying to set the model and the policies from the code itself, instead of loading from a file.

My test is failing because the enforcer is returning ```false``` when I wish it returned ```true```.

```rust
use casbin::prelude::*;
use futures_await_test::async_test;

pub async fn init_enforcer<A: TryIntoAdapter>(adapter: A) -> Result<casbin::Enforcer> {
    let model = DefaultModel::from_str(r#"
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && r.act == p.act
        "#).await?;
    let e = Enforcer::new(model, adapter).await?;
    Ok(e)
}

#[cfg(test)]
mod tests {
    // Note this useful idiom: importing names from outer (for mod tests) scope.
    use super::*;

    #[async_test]
    async fn test_enforcer() -> Result<()> {
        let mut e = init_enforcer(()).await?;
        let a = e.get_mut_adapter();
        a.add_policy("p", "p", vec!["alice".to_string(), "data1".to_string(), "read".to_string()]).await?;
        assert_eq!(true, e.enforce(&["alice", "data1", "read"])?);
        Ok(())
    }
}
```

This is my Cargo.toml:
```toml
[dependencies]
rocket = "0.4.5"
chrono = { version = "0.4", features = ["serde"]  }
sloggers = "1.0.1"
rust_decimal = "1.6.0"
slog-journald = "2.1.1"
casbin = { version = "1.1.0", default-features = false, features = ["runtime-async-std", "logging"] }
async-std = { version = "1.5.0", features = ["attributes"] }
futures-await-test = "0.3.0"
```
